### ISSUE TITLE
Error message ?!

### ISSUE THREAD

**Issue by SunSea88** [1024mb/APK-Info#8]
Hello,

With the release 1.41, whether it's the version 32 bits or the version 64 bits I have this result :-(

Then, what should I do please ?

![Image](https://github.com/user-attachments/assets/551994fa-d280-473d-8717-f7b7862f4651)

![Image](https://github.com/user-attachments/assets/5f6d808d-eef0-4b32-aaaa-4e276ac5fe70)

**Comment by 1024mb** [comment]
Execute `Setup_Additional_Tools.cmd` and wait for it to finish.

**Comment by SunSea88** [comment]
After this step, it's always the same result...

**Comment by 1024mb** [comment]
Post a screenshot of the output from `Setup_Additional_Tools.cmd`, it looks like it's not downloading anything.  
Otherwise you would have to download all the listed tools manually and store them in a `tools` directory on the same path the exe is located.

Edit: Btw the missing text on the error message should be fixed now.

**Comment by SunSea88** [comment]
![Image](https://github.com/user-attachments/assets/63643676-e5eb-4dec-847a-e40e700ed147)

> Otherwise you would have to download all the listed tools manually and store them in a `tools` directory on the same path the exe is located.

Sorry because I'm not an advanced user yet but I can follow the directions if you have the time to tell me what to do according to you.

**Comment by 1024mb** [comment]
it looks like your firewall or Anti-Virus is intercepting HTTPS connections, that's making curl error out.
You need to download these tools and extract them in a directory named "tools" on the same path the APK-Info.exe is located:

https://curl.se/windows/dl-8.13.0_3/curl-8.13.0_3-win64-mingw.zip
https://github.com/ip7z/7zip/releases/download/24.09/7z2409-extra.7z
https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-47-portable-Q16-x64.zip
https://dl.google.com/android/repository/platform-tools_r34.0.4-windows.zip
https://dl.google.com/android/repository/build-tools_r34-windows.zip

You have to extract the files so your tools directory contains (from the 7-zip package you have to extract 7za.exe and rename it to 7z.exe):
```
7z.exe
aapt.exe
aapt2.exe
adb.exe
AdbWinApi.dll
AdbWinUsbApi.dll
apksigner.jar
colors.xml
curl.exe
curl-ca-bundle.crt
libwinpthread-1.dll
magick.exe
```

I have modified the batch script to ignore TLS but you shouldn't normally be needing nor using this:
(remove the .txt extension)
[Setup_Additional_Tools_IgnoreTLS.cmd.txt](https://github.com/user-attachments/files/20071114/Setup_Additional_Tools_IgnoreTLS.cmd.txt)

**Comment by SunSea88** [comment]
Thank you very much for all the explanations and the solution : I disabled Kaspersky and everything works perfectly now ☺️

I also would like to know please :

-> Why the icons of some applications don't appear
-> It's possible to still have the redirection to https://apkpure.com and even https://www.apkmirror.com as on the version 1.35
-> It's possible to have in the future the analysis of these **APKM, APKS, XAPK** files too
-> It's possible to also have the API Levels Name because it's funny to have the following names of desserts :
->> **10 : Quince Tart, 11 : Red Velvet Cake, 12 : Snow Cone, 13 : Tiramisu, 14 : Upside Down Cake, 15 : Vanilla Ice Cream, 16 : Baklava**
-> It's possible to have the screen densities like this for a better overview :
->> **ldpi (120) mdpi (160) hdpi (240) xhdpi (320) xxhdpi (480) xxxhdpi (640)**

A small comparison of the versions 1.35 and 1.41

![Image](https://github.com/user-attachments/assets/ea8a528d-d9e6-45c4-b413-5d7c28067861)

![Image](https://github.com/user-attachments/assets/489a8ac3-4de6-4edc-b4c7-bf11531aee58)

**Comment by 1024mb** [comment]
> -> Why the icons of some applications don't appear

Because modern apps don't use plain image files for icons anymore, instead the adaptive icon is encoded in an xml file for which a parser/decoder is missing.

> -> It's possible to still have the redirection to [apkpure.com](https://apkpure.com/) and even [apkmirror.com](https://www.apkmirror.com/) as on the version 1.35

You have the option to open the selected website, if you are missing the button it must be that you forgot to change/enable the `CustomStore` option in the `user_config.ini` file.

> -> It's possible to have in the future the analysis of these APKM, APKS, XAPK files too

`APKS` is already supported, I think `APKM` files are similar so it shouldn't be hard to support it, I haven't seen an `XAPK` file so I can't say, will look into it when I have time but please open a new issue about this.

> -> It's possible to also have the API Levels Name because it's funny to have the following names of desserts :
> ->> 10 : Quince Tart, 11 : Red Velvet Cake, 12 : Snow Cone, 13 : Tiramisu, 14 : Upside Down Cake, 15 : Vanilla Ice Cream, 16 : Baklava

I think so, but where?

> -> It's possible to have the screen densities like this for a better overview :
> ->> ldpi (120) mdpi (160) hdpi (240) xhdpi (320) xxhdpi (480) xxxhdpi (640)

I'll look into adding such option but also please open a separate issue so I can keep track of this as this issue will be closed since the main problem is resolved.
